import { motion } from "motion/react";
import { Icon } from "../components/Icon";
const projects=[
 {name:"CodeFlow",subtitle:"Plataforma para aprender programação",description:"Ensino de programação do zero com aulas curtas, código rodando no próprio navegador e correção que explica o porquê do erro — inspirado no modelo do Duolingo.",stack:["React","TypeScript","Supabase","Vite"],repo:"https://github.com/EduuGah/CodeFlow",demo:"https://github.com/EduuGah/CodeFlow",images:["/projetos/codeflow.png","/projetos/codeflow-dashboard.png"]},
 {name:"DineFlow",subtitle:"Pedidos em tempo real para restaurantes",description:"Fluxo de pedidos entre atendimento e cozinha, com dados isolados por restaurante.",stack:["Next.js","TypeScript","Supabase"],repo:"https://github.com/EduuGah/DineFlow",demo:"https://dine-flow-zeta-snowy.vercel.app/",image:"/projetos/dineflow.png"},
 {name:"CutFlow",subtitle:"Gestão para barbearias",description:"Agenda, profissionais, serviços e horários reunidos em uma aplicação de gestão.",stack:["React","TypeScript","Node.js","PostgreSQL"],repo:"https://github.com/EduuGah/CutFlow",demo:"https://cut-flow-sandy.vercel.app/",image:"/projetos/cutflow.png"},
 {name:"ForgeFlow",subtitle:"Treino e evolução de cargas",description:"Aplicação para montar fichas, registrar treinos e acompanhar evolução de cargas.",stack:["React","TypeScript","Vite","Kotlin"],repo:"https://github.com/EduuGah/ForgeFlow",demo:"https://forge-flow-five.vercel.app/",image:"/projetos/forgeflow.png"},
 {name:"CoupleFlow",subtitle:"Organização compartilhada para casais",description:"Espaço para organizar ideias, atividades e planos compartilhados em um só lugar.",stack:["React","TypeScript","Firebase"],repo:"https://github.com/EduuGah/CoupleFlow",demo:"https://couple-flow.vercel.app/",image:"/projetos/coupleflow.png"}
];
export function Projects(){return <section id="projetos" className="section projects"><div className="section-heading"><p className="kicker">03 / Projetos</p><h2>Projetos em destaque.</h2><p>Alguns dos projetos que desenvolvi para praticar produto, interface e integração.</p></div><div className="projects-grid">{projects.map((p,i)=><motion.article className="project-card" key={p.name} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.4,delay:i*.05}}><a className="project-image-container" href={p.demo} target="_blank" rel="noreferrer" aria-label={`Abrir ${p.name}`}>{p.images?<div className="project-image-split">{p.images.map(src=><img src={src} alt={`Tela do projeto ${p.name}`} className="project-screenshot" key={src} loading="lazy"/>)}</div>:<img src={p.image} alt={`Tela do projeto ${p.name}`} className="project-screenshot" loading="lazy"/>}</a><div className="project-content"><div className="project-title-row"><div><h3>{p.name}</h3><strong className="project-subtitle">{p.subtitle}</strong></div></div><p>{p.description}</p><div className="tags">{p.stack.map(x=><span className="badge" key={x}>{x}</span>)}</div><div className="project-links"><a className="demo-link" href={p.demo} target="_blank" rel="noreferrer"><Icon name="external" size={15}/> Projeto</a><a href={p.repo} target="_blank" rel="noreferrer"><Icon name="github" size={16}/> GitHub</a></div></div></motion.article>)}</div></section>}
